apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: receptify

resources:
  - namespace.yaml
  - cert-issuer.yaml
  - secrets.yaml
  - postgres.yaml
  - receptify-api.yaml
  - receptify-frontend.yaml
  - agent.yaml
  - fs-bridge.yaml
  - rag-service.yaml
  - stt-service.yaml
  - tts-service.yaml
